version: '3'
services:
  qqbot:
    image: asupc/qqbot
    restart: always
    privileged: true
    container_name: qqbot1
    ports:
      - 5010:5010
    volumes:
      - ./app:/app
    environment:
      - TZ=Asia/Shanghai